### ISSUE TITLE
Move the topic parameters down one level

### ISSUE THREAD

**Issue by clalancette** [osrf/ros2_serial_example#55]
Right now the YAML file for configuration looks like this:

```
ros2_to_serial_bridge:
    ros__parameters:
        device: /dev/pts/25
        serial_protocol: px4
        chatter:
            serial_mapping: 9
            type: std_msgs/String
            direction: SerialToROS2
```

The problem is that the topic -> serial mapping parts aren't in their own section, so they aren't cleanly separated from the rest of the configuration.  We should move them down one level under a high-level "topics" sub-category to clearly delineate them.
